global_frame: map

robot_base_frame: base_footprint

update_frequency: 10.0

publish_frequency: 10.0

rolling_window: true

width: 10         # default: 10
height: 10         # default: 10

resolution: 0.025   # default: 0.05
origin_x: 0.0       # default: 0.0
origin_y: 0.0       # default: 0.0

plugins:
  - {name: obstacles, type: "costmap_2d::ObstacleLayer"}
  - {name: inflation, type: "costmap_2d::InflationLayer"}
  - {name: simple, type: "object_layer::SimpleLayer"}
  - {name: grid, type: "object_layer::GridLayer"}

